import { LiaOldRepublic } from 'react-icons/lia';
import { captoe, chukkaboot, splittoe, tasselloafer, wholecut, doublemonk, belt } from './src/assets/index';

export const items = [
  {
    id: 1,
    name: "Cap-Toe Oxford",
    price: 53.00,
    discountPrice: "$60.00",
    category: "Shoes",
    images: [
      { src: captoe, bg: '#001e21' },
      { src: captoe, bg: '#00454c' },
      { src: captoe, bg: '#4c0700' },
    ],
    image: captoe,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★☆",
    reviews: "6 customer review",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Split Toe Derby",
    price: 32.00,
    discountPrice: "$40.00",
    category: "Shoes",
    images: [
      { src: splittoe, bg: '#001e21' },
      { src: splittoe, bg: '#00454c' },
      { src: splittoe, bg: '#4c0700' },
    ],
    image: splittoe,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",  
    star: "★★★★★",
    reviews: "8 customer review",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Chukka Boot",
    price: 25.00,
    discountPrice: "$30.00",
    category: "Shoes",
    images: [
      { src: chukkaboot, bg: '#001e21' },
      { src: chukkaboot, bg: '#00454c' },
      { src: chukkaboot, bg: '#4c0700' },
    ],
    image: chukkaboot,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★★",
    reviews: "10 customer review",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Tassel Loafer",
    price: 65.00,
    discountPrice: "$70.00",
    category: "Shoes",
    images: [
      { src: tasselloafer, bg: '#001e21' },
      { src: tasselloafer, bg: '#00454c' },
      { src: tasselloafer, bg: '#4c0700' },
    ],
    image: tasselloafer,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★",
    reviews: "4 customer review",
    availability: "Out Of Stock",
  },
  {
    id: 5,
    name: "Wholecut Oxford",
    price: 30.00,
    discountPrice: "$35.00",
    category: "Shoes",
    images: [
      { src: wholecut, bg: '#001e21' },
      { src: wholecut, bg: '#00454c' },
      { src: wholecut, bg: '#4c0700' },
    ],
    image: wholecut,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★☆",
    reviews: "5 customer review",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Double Monk",
    price: 18.00,
    discountPrice: "$20.00",
    category: "Shoes",
    images: [
      { src: doublemonk, bg: '#001e21' },
      { src: doublemonk, bg: '#00454c' },
      { src: doublemonk, bg: '#4c0700' },
    ],
    image: doublemonk,
    text: "Make a statement with our stylish and comfortable shoes.",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★★",
    reviews: "12 customer review",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Chealsea Boot",
    price: 45.00,
    discountPrice: "$50.00",
    category: "Shoes",
    images: [
      { src: captoe, bg: '#001e21' },
      { src: captoe, bg: '#00454c' },
      { src: captoe, bg: '#4c0700' },
    ],
    image: captoe,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★★",
    reviews: "6 customer review",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Brogue Derby",
    price: 55.00,
    discountPrice: "$60.00",
    category: "Shoes",
    images: [
      { src: chukkaboot, bg: '#001e21' },
      { src: chukkaboot, bg: '#00454c' },
      { src: chukkaboot, bg: '#4c0700' },
    ],
    image: chukkaboot,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★★",
    reviews: "10 customer review",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Plain-Toe Blucher",
    price: 70.00,
    discountPrice: "$80.00",
    category: "Shoes",
    images: [
      { src: wholecut, bg: '#001e21' },
      { src: wholecut, bg: '#00454c' },
      { src: wholecut, bg: '#4c0700' },
    ],
    image: wholecut,
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★",
    reviews: "7 customer review",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Hand Bag",
    price: 90.00,
    discountPrice: "$100.00",
    category: "Bags",
    images: [
      { src: "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png", bg: '#001e21' },
      { src: "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png", bg: '#00454c' },
      { src: "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png", bg: '#4c0700' },
    ],
    image: "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png",
    text: "Make a statement with our stylish and comfortable bags.",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★★",
    reviews: "8 customer review",
    availability: "Out Of Stock",
  },
  {
    id: 11,
    name: "Shoulder Bag",
    price: 90.00,
    discountPrice: "$100.00",
    category: "Bags",
    images: [
      { src: "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png", bg: '#001e21' },
      { src: "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png", bg: '#00454c' },
      { src: "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png", bg: '#4c0700' },
    ],
    image:  "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png",
    text: "Give your feet the beauty treatment that only brand new shoes can give",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★★",
    reviews: "8 customer review",
    availability: "Out Of Stock",
  },
  {
    id: 12,
    name: "Tote Bag",
    price: 90.00,
    discountPrice: "$100.00",
    category: "Bags",
    images: [
      { src: "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png", bg: '#001e21' },
      { src: "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png", bg: '#00454c' },
      { src: "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png", bg: '#4c0700' },
    ],
    image: "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png",
    text: "Make a statement with our stylish and comfortable bags.",
    productDetails: "Good for all occasions and seasons.",
    star: "★★★★★",
    reviews: "8 customer review",
    availability: "Out Of Stock",
  },
  {
    id: 13,
    name: "Belt",
    price: 50.00,
    discountPrice: "$60.00",
    category: "Belts",
    images: [
      { src: belt, bg: '#001e21' },
      { src: belt, bg: '#00454c' },
      { src: belt, bg: '#4c0700' },
    ],
    image: belt,
    text: "Make a statement with our stylish and comfortable bags.",
    productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    star: "★★★★☆",
    reviews: "9 customer review",
    availability: "In Stock",
  },
];
