import { captoe, chukkaboot, splittoe, tasselloafer, wholecut, doublemonk, belt} from './src/assets/index';

export const items = [
    {
      id: 1,
      name: "Cap-Toe Oxford",
      price: 53.00,
      discountPrice: "$60.00",
      category: "Shoes",
      images: [
        { src: captoe, bg: '#f3f4f6' },
        { src: captoe, bg: '#FFFCF1' },
        { src: captoe, bg: '#000000' },
      ],
      image: captoe,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★☆",
      reviews: "6 customer review",
      availability: "In Stock",
    },
    {
      id: 2,
      name: "Split Toe Derby",
      price: 32.00,
      discountPrice: "$40.00",
      category: "Shoes",
      images: [
        { src: splittoe, bg: '#f3f4f6' },
        { src: splittoe, bg: '#FFFCF1' },
        { src: splittoe, bg: '#000000' },
      ],
      image: splittoe,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "8 customer review",
      availability: "In Stock",
    },
    {
      id: 3,
      name: "Chukka Boot",
      price: 25.00,
      discountPrice: "$30.00",
      category: "Shoes",
      images: [
        { src: chukkaboot, bg: '#f3f4f6' },
        { src: chukkaboot, bg: '#FFFCF1' },
        { src: chukkaboot, bg: '#000000' },
      ],
      image: chukkaboot,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "10 customer review",
      availability: "In Stock",
    },
    {
      id: 4,
      name: "Tassel Loafer",
      discountPrice: "$70.00",
      price: 65.00,
      category: "Shoes",
      images: [
        { src: tasselloafer, bg: '#f3f4f6' },
        { src: tasselloafer, bg: '#FFFCF1' },
        { src: tasselloafer, bg: '#000000' },
      ],
      image: tasselloafer,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★",
      reviews: "4 customer review",
      availability: "Out Of Stock",
    },
    {
      id: 5,
      name: "Wholecut Oxford",
      discountPrice: "$35.00",
      price: 30.00,
      category: "Shoes",
      images: [
        { src: wholecut, bg: '#f3f4f6' },
        { src: wholecut, bg: '#FFFCF1' },
        { src: wholecut, bg: '#000000' },
      ],
      image: wholecut,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★☆",
      reviews: "5 customer review", 
      availability: "In Stock",
    },
    {
      id: 6,
      name: "Double Monk",
      discountPrice: "$20.00",
      price: 18.00,
      category: "Shoes",
      images: [
        { src: doublemonk, bg: '#f3f4f6' },
        { src: doublemonk, bg: '#FFFCF1' },
        { src: doublemonk, bg: '#000000' },
      ],
      image: doublemonk,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "12 customer review",
      availability: "In Stock",
    },
    {
      id: 7,
      name: "Chealsea Boot",
      discountPrice: "$50.00",
      price: 45.00,
      category: "Shoes",
      images: [
        { src: captoe, bg: '#f3f4f6' },
        { src: captoe, bg: '#FFFCF1' },
        { src: captoe, bg: '#000000' },
      ],
      image: captoe,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "6 customer review",
      availability: "In Stock",
    },
    {
      id: 8,
      name: "Brogue Derby",
      price: 55.00,
      discountPrice: "$60.00",
      category: "Shoes",
      images: [
        { src: chukkaboot, bg: '#f3f4f6' },
        { src: chukkaboot, bg: '#FFFCF1' },
        { src: chukkaboot, bg: '#000000' },
      ],
      image: chukkaboot,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "10 customer review",
      availability: "In Stock",
    },
    {
      id: 9,
      name: "Plain-Toe Blucher",
      discountPrice: "$80.00",
      price: 70.00,
      category: "Shoes",
      images: [
        { src: wholecut, bg: '#f3f4f6' },
        { src: wholecut, bg: '#FFFCF1' },
        { src: wholecut, bg: '#000000' },
        
      ],
      image: wholecut,
      text: "Give your feet the beauty treatment that only brand new shoes can give",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★",
      reviews: "7 customer review",
      availability: "In Stock",
    },
    {
      id: 10,
      name: "Hand Bag",
      discountPrice: "$100.00",
      price: 90.00,
      category: "Bags",
      images: [
        { src:  "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png", bg: '#f3f4f6'},
        { src:  "https://static.vecteezy.com/system/resources/previews/022/914/882/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png", bg: '#FFFCF1' },
        { src:  "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png", bg: '#000000' },
      ],
      image: "https://static.vecteezy.com/system/resources/previews/022/914/876/non_2x/black-leather-bag-isolated-on-transparent-background-free-png.png",
      text: "The perfect accessory to complete your outfit",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "8 customer review",
      availability: "Out Of Stock",
    },
    {
      id: 11,
      name: "Shoulder Bag",
      discountPrice: "$100.00",
      price: 90.00,
      category: "Bags",
      images: [
        { src:  "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png", bg: '#f3f4f6'},
        { src:  "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png", bg: '#FFFCF1' },
        { src:  "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png", bg: '#000000' },
      ],
      image: "https://static.vecteezy.com/system/resources/previews/047/489/790/non_2x/black-leather-messenger-bag-with-shoulder-strap-and-buckle-closure-on-transparent-background-ai-generative-free-png.png",
      text: "The perfect accessory to complete your outfit",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "8 customer review",
      availability: "Out Of Stock",
    },
    {
      id: 12,
      name: "Tote Bag",
      discountPrice: "$100.00",
      price: 90.00,
      category: "Bags",
      images: [
        { src:  "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png", bg: '#f3f4f6'},
        { src:  "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png", bg: '#FFFCF1' },
        { src:  "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png", bg: '#000000' },
      ],
      image: "https://www.transparentpng.com/thumb/women-bag/P2gBbx-blue-women-bag-transparent-background.png",
      text: "The perfect accessory to complete your outfit",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★★",
      reviews: "8 customer review",
      availability: "Out Of Stock",
    },
    {
      id: 13,
      name: "Belt",
      price: 50.00,
      discountPrice: "$60.00",
      category: "Belts",
      images: [
        { src: belt, bg: '#f3f4f6' },
        { src: belt, bg: '#FFFCF1' },
        { src: belt, bg: '#000000' },
      ],
      image: belt,
      text: "The perfect accessory to complete your outfit",
      productDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      star: "★★★★☆",
      reviews: "9 customer review",
      availability: "In Stock",
      
    },

  ];